version: '3.4'

services:
  postgres_dev:
    restart: unless-stopped
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'web'
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: timootten@icloud.com
      PGADMIN_DEFAULT_PASSWORD: dev
    volumes:
      - pgadmin-dev-data:/var/lib/pgadmin

volumes:
  postgres-dev-data:
  pgadmin-dev-data:
